[tool.black]
line-length = 120
target-version = ["py312"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
files = ["ml-demos", "tests"]
ignore_missing_imports = true
strict = true
